### ISSUE TITLE
Set up backup delivery platform account

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/CNS-2020#5]

**Comment by appukuttan-shailesh** [comment]
As per our discussions, I believe we intend to go with Zoom as the backup platform.
I am curious about what we intend here by "setting up". I presume we don't intend to buy a subscription on the second platform as well. And without the subscription, would we be in a position to setup (or test) these platforms, owing to limitations of the free accounts?

**Comment by sanjayankur31** [comment]
I think we will need to buy a subscription: the free accounts are still limited to 40 minutes and lack lots of features. We could check to see if members of the WOC have paid subscriptions already that could be used for this perhaps?
